spring:
  datasource:
    url: jdbc:mysql://localhost:3306/chat-app
    username: 
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
    thymeleaf:
    cache: false
  jpa:
    hibernate.ddl-auto: update
  application:
    name: todo-app
server:
  port: 8080



